services:
  # --- INGESTION & ACTUATION ---

  rest-poller:
    build: ./source/backend/ingestion
    container_name: rest-poller
    platform: linux/amd64
    command: ["python", "-u", "rest_poller.py"]
    depends_on:
      - simulator
      - activemq
    environment:
      - BROKER_HOST=activemq
    restart: always

  stream-subscriber:
    build: ./source/backend/ingestion
    container_name: stream-subscriber
    platform: linux/amd64
    command: ["python", "-u", "stream_subscriber.py"]
    depends_on:
      - simulator
      - activemq
    environment:
      - BROKER_HOST=activemq
    restart: always

  actuator-executor:
    build: ./source/backend/ingestion
    container_name: actuator-executor
    platform: linux/amd64
    command: ["python", "-u", "consumer.py"]
    depends_on:
      - simulator
      - activemq
    environment:
      - BROKER_HOST=activemq
      - SIMULATOR_HOST=simulator
    restart: always

  # --- AUTOMATION LOGIC ---

  automation:
    build: ./source/backend/automation
    container_name: automation-engine
    platform: linux/amd64
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:                 
      - "8000:8000"        
    depends_on:
      - activemq
    environment:
      - BROKER_HOST=activemq
    restart: always
    volumes:
      - sqlite_data:/app/data

  # --- FRONTEND ---

  frontend:
    build: ./source/frontend
    container_name: mars-frontend
    platform: linux/amd64
    ports:
      - "8081:8081"
    depends_on:
      - activemq
    restart: always

  # --- INFRASTRUCTURE ---



  simulator:
    image: mars-iot-simulator:multiarch_v1
    container_name: mars_simulator
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    platform: linux/amd64
    ports:
      - "61613:61613" # Porta per STOMP (Python)
      - "8161:8161"   # Console Web (Admin)
    environment:
      - ACTIVEMQ_ADMIN_USER=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    restart: always

# --- FINE SERVICES ---

volumes:       
  sqlite_data: